# Generated by Django 3.1.3 on 2020-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointermarker',
            name='nome_local',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
